name: C CI/CD with GoogleTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: sudo apt-get install -y cmake build-essential

    - name: Build the application
      run: make

    - name: Run application
      run: ./main

    - name: Build tests
      run: make test

    - name: Run tests
      run: ./test
